logging:
  level:
    org.springframework.web: DEBUG

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:mydb;MODE=MySQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  flyway:
    locations: classpath:db/migration